### ISSUE TITLE
Illegal moves allowed

### ISSUE THREAD

**Issue by anpd03** [paviad/GoSharp#10] opened 2017-07-30 20:03 UTC
Looks like you are allowed to fill you last liberty if it's a group of more than one stone. 1 stone is not allowed to play a suicide move but a group is.

**Comment by paviad** [comment] 2017-08-01 12:37
This is by design, look at the documentation for MakeMove:

```
Makes a move and returns a new Game object representing the state after the
move. The move is carried out whether it is legal or illegal (for example,
an overwrite move). The color of the move is determined by the Turn property.
the move was illegal (suicide, violating super-ko, or an overwrite), the
sets the legal parameter to false, otherwise it is set to true.
```

The method returns whether the move was legal or illegal, and sets the `IsLegal` member on the Game object accordingly.

**Comment by anpd03** [comment] 2017-08-01 18:28
Yes aware of how it works, but the error is that the move to fill a groups last liberty is considered legal. 

Here is the code I use.

bool legal;
				Game postMove = game.MakeMove(selectedTileX, selectedTileY, out legal);

				if( legal)
				{ 
					game = postMove;

					lastMove = new Point(selectedTileX, selectedTileY);
					string move = fileLetters[selectedTileX] + (selectedTileY+1).ToString();
					
					playSound = true;
					numPasses = 0;
				}

And here is a gif where I am not allowed to play in the ponnuki but allowed to fill the groups last liberty https://www.dropbox.com/s/x5eia9of61aio39/capture.gif?dl=0

**Comment by paviad** [comment] 2017-08-02 08:08
You're right, it's fixed now.

**Closed by paviad** 2017-08-02 08:08 UTC

**Comment by anpd03** [comment] 2017-08-02 16:34
Thanks!
